version: "3.9"
name: autotrace
services:
  app:
    build:
      context: .
    entrypoint: /autotrace/entrypoint.sh
    volumes:
      - ./inputs:/autotrace/inputs
      - ./outputs:/autotrace/outputs
    tmpfs:
      - /tmp
